### ISSUE TITLE
Марсианские новости

### ISSUE THREAD

**Issue by hombit** [hombit/sai-tasks2019#10]
Напишите веб-сайт, который для указанной даты показывает фото, снятое [марсоходом](https://github.com/chrisccerami/mars-photo-api), и выписку из статьи Википедии о том, что случилось в этот день на Земле

Не выкладывайте API-ключ в открытый доступ!

**Comment by AndreyTavleev** [comment]
Давайте-ка я это возьму.

**Comment by hombit** [comment]
Fixed in #23
