### ISSUE TITLE
Ясное небо на КГО

### ISSUE THREAD

**Issue by hombit** [hombit/sai-tasks2019#15]
Используя запросы к InfluxDB, работающей на http://eagle.sai.msu.ru, напишите скрипт, подсчитывающий сколько было за год часов ясного неба на КГО для высоты Солнца -12 и -18 градусов

Описание базы:

http://eagle.sai.msu.ru/query?db=taxandria&q=SHOW%20measurements
http://eagle.sai.msu.ru/query?db=collectd&q=SHOW%20measurements

**Comment by Kirsankina** [comment]
Я сделаю эту
