### ISSUE TITLE
Запуск Марсианских новостей через wsgi

### ISSUE THREAD

**Issue by hombit** [hombit/sai-tasks2019#30]
В марсианских новостях #10 глобальная переменная с API-ключем используется внутри блока `if __name__ == '__main__'`. Во-первых, не стоит вводить глобальные переменные ниже кода, их использующего, еще и внутри условных операторов. Во-вторых при запуске через wsgi (а так должны [в продакшене запускать все сервера на Flask](https://flask.palletsprojects.com/en/1.1.x/tutorial/deploy/#run-with-a-production-server)) получается, что этой переменной не существует

Проще всего просто вынести код, который определяет NASA_API_key в начало файла, оставив его глобальным

Также стоит переименовать site.py во что-нибудь, что не перекликается со [стандартной библиотекой](https://docs.python.org/3/library/site.html)

**Comment by AndreyTavleev** [comment]
Создал pull request с исправлением.

**Comment by hombit** [comment]
Fixed by #31
